#!/bin/bash

echo "╔════════════════════════════════════════════════════════════╗"
echo "║              启用真实交易 - 快速部署                        ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

echo "📊 您的配置信息："
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "API Key:        019cc244-caab-7bf1-884e-61392538582e"
echo "API Secret:     HS5QdfZ0Yq7kqhXLSEpy90aS6V9_liZe5OWz6PTymNY="
echo "Wallet Key:     0x89a07674466649a1a49b170fbf8abb5358041a70e37d8b6311216d2b33f64c93"
echo "Position Size:  100 USDC"
echo "Max Exposure:   1000 USDC"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "🚀 快速部署选项："
echo ""
echo "【选项 1】Vercel 部署（推荐）"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "步骤："
echo "1. 访问 https://vercel.com/new"
echo "2. 导入您的 Git 仓库"
echo "3. 添加上面列出的环境变量"
echo "4. 点击 Deploy"
echo ""
echo "详细步骤: cat VERCEL_DEPLOY.md"
echo ""

echo "【选项 2】本地运行"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "如果您有本地开发环境："
echo ""
echo "1. 克隆项目到本地"
echo "2. 复制 .env.local 文件"
echo "3. 运行: pnpm install && pnpm dev"
echo "4. 访问: http://localhost:5000"
echo ""

echo "【选项 3】导出项目"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "导出项目文件："
echo "  tar -czf polymarket-trading.tar.gz \\"
echo "    --exclude='node_modules' --exclude='.next' ."
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⚠️  部署前准备："
echo ""
echo "1. 钱包资金"
echo "   • USDC (Polygon): 50-100 USDC"
echo "   • MATIC (Polygon): 1-2 MATIC"
echo ""
echo "2. 钱包地址"
echo "   导入私钥到 MetaMask 查看钱包地址"
echo ""
echo "3. Git 仓库"
echo "   确保代码已推送到 GitHub/GitLab"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📚 帮助文档："
echo ""
echo "  cat VERCEL_DEPLOY.md        - Vercel详细部署步骤"
echo "  cat DEPLOY_REAL_TRADING.md  - 完整部署指南"
echo "  cat DEPLOYMENT.md           - 系统部署文档"
echo ""
