#!/bin/bash

echo "╔════════════════════════════════════════════════════════════╗"
echo "║         Polymarket 交易系统 - 真实交易部署向导              ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

echo "请选择部署方式："
echo ""
echo "  1️⃣  Vercel（推荐 - 免费托管平台）"
echo "     • 免费使用"
echo "     • 自动HTTPS"
echo "     • 简单易用"
echo ""
echo "  2️⃣  Railway（简单部署平台）"
echo "     • 免费额度"
echo "     • 自动部署"
echo ""
echo "  3️⃣  自己的服务器（完全控制）"
echo "     • 需要自己的服务器"
echo "     • 完全自定义"
echo ""
echo "  4️⃣  Docker（容器化部署）"
echo "     • 可在任何平台运行"
echo "     • 易于迁移"
echo ""
echo "  5️⃣  导出代码（手动部署）"
echo "     • 下载项目代码"
echo "     • 自行部署"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

read -p "请输入选项 (1-5): " choice

case $choice in
    1)
        echo ""
        echo "🚀 Vercel 部署"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        echo "准备步骤："
        echo ""
        echo "1. 确保代码已提交到 Git 仓库"
        echo "   git add . && git commit -m 'Deploy to production'"
        echo "   git push"
        echo ""
        echo "2. 访问 Vercel"
        echo "   https://vercel.com/new"
        echo ""
        echo "3. 导入您的 Git 仓库"
        echo ""
        echo "4. 添加环境变量（重要！）"
        echo "   POLYMARKET_API_KEY=019cc244-caab-7bf1-884e-61392538582e"
        echo "   POLYMARKET_API_SECRET=HS5QdfZ0Yq7kqhXLSEpy90aS6V9_liZe5OWz6PTymNY="
        echo "   WALLET_PRIVATE_KEY=0x89a07674466649a1a49b170fbf8abb5358041a70e37d8b6311216d2b33f64c93"
        echo "   POSITION_SIZE=100"
        echo "   MAX_EXPOSURE=1000"
        echo ""
        echo "5. 点击 Deploy"
        echo ""
        echo "详细说明: cat DEPLOY_REAL_TRADING.md"
        ;;
    2)
        echo ""
        echo "🚀 Railway 部署"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        echo "运行命令："
        echo ""
        echo "npm i -g @railway/cli"
        echo "railway login"
        echo "railway init"
        echo "railway variables set POLYMARKET_API_KEY=019cc244-caab-7bf1-884e-61392538582e"
        echo "railway variables set POLYMARKET_API_SECRET=HS5QdfZ0Yq7kqhXLSEpy90aS6V9_liZe5OWz6PTymNY="
        echo "railway variables set WALLET_PRIVATE_KEY=0x89a07674466649a1a49b170fbf8abb5358041a70e37d8b6311216d2b33f64c93"
        echo "railway variables set POSITION_SIZE=100"
        echo "railway variables set MAX_EXPOSURE=1000"
        echo "railway up"
        echo ""
        echo "详细说明: cat DEPLOY_REAL_TRADING.md"
        ;;
    3)
        echo ""
        echo "🚀 自己的服务器部署"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        echo "在您的服务器上执行："
        echo ""
        echo "1. 克隆项目"
        echo "   git clone <your-repo>"
        echo "   cd polymarket-arbitrage"
        echo ""
        echo "2. 安装依赖"
        echo "   pnpm install"
        echo ""
        echo "3. 创建 .env.local 文件"
        echo "   （复制您当前的配置）"
        echo ""
        echo "4. 构建并启动"
        echo "   pnpm build"
        echo "   pnpm start"
        echo ""
        echo "详细说明: cat DEPLOY_REAL_TRADING.md"
        ;;
    4)
        echo ""
        echo "🚀 Docker 部署"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        echo "构建并运行："
        echo ""
        echo "docker build -t polymarket-trading ."
        echo ""
        echo "docker run -d -p 5000:5000 \\"
        echo "  -e POLYMARKET_API_KEY=019cc244-caab-7bf1-884e-61392538582e \\"
        echo "  -e POLYMARKET_API_SECRET=HS5QdfZ0Yq7kqhXLSEpy90aS6V9_liZe5OWz6PTymNY= \\"
        echo "  -e WALLET_PRIVATE_KEY=0x89a07674466649a1a49b170fbf8abb5358041a70e37d8b6311216d2b33f64c93 \\"
        echo "  -e POSITION_SIZE=100 \\"
        echo "  -e MAX_EXPOSURE=1000 \\"
        echo "  --name trading-bot \\"
        echo "  polymarket-trading"
        echo ""
        echo "详细说明: cat DEPLOY_REAL_TRADING.md"
        ;;
    5)
        echo ""
        echo "📦 导出项目代码"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        echo "项目文件列表："
        echo ""
        find . -type f -name "*.ts" -o -name "*.tsx" -o -name "*.json" -o -name "*.md" | grep -v node_modules | grep -v ".next" | head -30
        echo ""
        echo "配置文件："
        echo "  .env.local - 已配置"
        echo ""
        echo "导出命令："
        echo "  tar -czf polymarket-trading.tar.gz \\"
        echo "    --exclude='node_modules' \\"
        echo "    --exclude='.next' \\"
        echo "    ."
        echo ""
        echo "然后上传到您的服务器"
        ;;
    *)
        echo "无效选项"
        exit 1
        ;;
esac

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ 准备就绪！"
echo ""
echo "⚠️  重要提醒："
echo "• 确保钱包有 USDC 和 MATIC（Polygon网络）"
echo "• 建议先用小额资金测试"
echo "• 部署后访问监控面板验证"
echo "• 观察第一笔交易执行情况"
echo ""
